packages:
  - apps/client
  - apps/server
  - libraries/contracts
  - providers/dkbus
  - providers/flowly
  - providers/idelis
  - providers/gtfs
  - providers/hawk
  - providers/twisto
  - providers/tcl
  - providers/rtm

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@swc/core'
  - esbuild
  - protobufjs
  - sharp
