packages:
  - apps/client
  - apps/server
  - libraries/contracts
  - providers/dkbus
  - providers/flowly
  - providers/idelis
  - providers/gtfs
  - providers/hawk
  - providers/twisto
  - providers/tcl
  - providers/rtm

allowUnusedPatches: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - protobufjs
  - sharp

patchedDependencies:
  '@danielgtmn/umami-react@1.1.1': patches/@danielgtmn__umami-react@1.1.1.patch
