/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as EmbedNetworkIdRouteImport } from './routes/embed/$networkId'
import { Route as AppLegalRouteImport } from './routes/_app/legal'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppDataIndexRouteImport } from './routes/_app/data/index'
import { Route as AppDataVehiclesVehicleIdRouteImport } from './routes/_app/data/vehicles/$vehicleId'
import { Route as AppDataNetworksNetworkIdRouteImport } from './routes/_app/data/networks/$networkId'
import { Route as AppDataLinesLineIdIndexRouteImport } from './routes/_app/data/lines/$lineId/index'
import { Route as AppDataLinesLineIdVehicleAssignmentsRouteImport } from './routes/_app/data/lines/$lineId/vehicle-assignments'
import { Route as AppDataLinesLineIdGirouettesRouteImport } from './routes/_app/data/lines/$lineId/girouettes'
import { Route as AppDataLinesLineIdGirouettesNewRouteImport } from './routes/_app/data/lines/$lineId/girouettes_.new'
import { Route as AppDataLinesLineIdGirouettesGirouetteIdEditRouteImport } from './routes/_app/data/lines/$lineId/girouettes_.$girouetteId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const EmbedNetworkIdRoute = EmbedNetworkIdRouteImport.update({
  id: '/embed/$networkId',
  path: '/embed/$networkId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDataIndexRoute = AppDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataVehiclesVehicleIdRoute =
  AppDataVehiclesVehicleIdRouteImport.update({
    id: '/data/vehicles/$vehicleId',
    path: '/data/vehicles/$vehicleId',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataNetworksNetworkIdRoute =
  AppDataNetworksNetworkIdRouteImport.update({
    id: '/data/networks/$networkId',
    path: '/data/networks/$networkId',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataLinesLineIdIndexRoute = AppDataLinesLineIdIndexRouteImport.update({
  id: '/data/lines/$lineId/',
  path: '/data/lines/$lineId/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataLinesLineIdVehicleAssignmentsRoute =
  AppDataLinesLineIdVehicleAssignmentsRouteImport.update({
    id: '/data/lines/$lineId/vehicle-assignments',
    path: '/data/lines/$lineId/vehicle-assignments',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataLinesLineIdGirouettesRoute =
  AppDataLinesLineIdGirouettesRouteImport.update({
    id: '/data/lines/$lineId/girouettes',
    path: '/data/lines/$lineId/girouettes',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataLinesLineIdGirouettesNewRoute =
  AppDataLinesLineIdGirouettesNewRouteImport.update({
    id: '/data/lines/$lineId/girouettes_/new',
    path: '/data/lines/$lineId/girouettes/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataLinesLineIdGirouettesGirouetteIdEditRoute =
  AppDataLinesLineIdGirouettesGirouetteIdEditRouteImport.update({
    id: '/data/lines/$lineId/girouettes_/$girouetteId/edit',
    path: '/data/lines/$lineId/girouettes/$girouetteId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/help': typeof AppHelpRoute
  '/legal': typeof AppLegalRoute
  '/embed/$networkId': typeof EmbedNetworkIdRoute
  '/data/': typeof AppDataIndexRoute
  '/data/networks/$networkId': typeof AppDataNetworksNetworkIdRoute
  '/data/vehicles/$vehicleId': typeof AppDataVehiclesVehicleIdRoute
  '/data/lines/$lineId/girouettes': typeof AppDataLinesLineIdGirouettesRoute
  '/data/lines/$lineId/vehicle-assignments': typeof AppDataLinesLineIdVehicleAssignmentsRoute
  '/data/lines/$lineId/': typeof AppDataLinesLineIdIndexRoute
  '/data/lines/$lineId/girouettes/new': typeof AppDataLinesLineIdGirouettesNewRoute
  '/data/lines/$lineId/girouettes/$girouetteId/edit': typeof AppDataLinesLineIdGirouettesGirouetteIdEditRoute
}
export interface FileRoutesByTo {
  '/help': typeof AppHelpRoute
  '/legal': typeof AppLegalRoute
  '/embed/$networkId': typeof EmbedNetworkIdRoute
  '/': typeof AppIndexRoute
  '/data': typeof AppDataIndexRoute
  '/data/networks/$networkId': typeof AppDataNetworksNetworkIdRoute
  '/data/vehicles/$vehicleId': typeof AppDataVehiclesVehicleIdRoute
  '/data/lines/$lineId/girouettes': typeof AppDataLinesLineIdGirouettesRoute
  '/data/lines/$lineId/vehicle-assignments': typeof AppDataLinesLineIdVehicleAssignmentsRoute
  '/data/lines/$lineId': typeof AppDataLinesLineIdIndexRoute
  '/data/lines/$lineId/girouettes/new': typeof AppDataLinesLineIdGirouettesNewRoute
  '/data/lines/$lineId/girouettes/$girouetteId/edit': typeof AppDataLinesLineIdGirouettesGirouetteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/help': typeof AppHelpRoute
  '/_app/legal': typeof AppLegalRoute
  '/embed/$networkId': typeof EmbedNetworkIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/data/': typeof AppDataIndexRoute
  '/_app/data/networks/$networkId': typeof AppDataNetworksNetworkIdRoute
  '/_app/data/vehicles/$vehicleId': typeof AppDataVehiclesVehicleIdRoute
  '/_app/data/lines/$lineId/girouettes': typeof AppDataLinesLineIdGirouettesRoute
  '/_app/data/lines/$lineId/vehicle-assignments': typeof AppDataLinesLineIdVehicleAssignmentsRoute
  '/_app/data/lines/$lineId/': typeof AppDataLinesLineIdIndexRoute
  '/_app/data/lines/$lineId/girouettes_/new': typeof AppDataLinesLineIdGirouettesNewRoute
  '/_app/data/lines/$lineId/girouettes_/$girouetteId/edit': typeof AppDataLinesLineIdGirouettesGirouetteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/legal'
    | '/embed/$networkId'
    | '/data/'
    | '/data/networks/$networkId'
    | '/data/vehicles/$vehicleId'
    | '/data/lines/$lineId/girouettes'
    | '/data/lines/$lineId/vehicle-assignments'
    | '/data/lines/$lineId/'
    | '/data/lines/$lineId/girouettes/new'
    | '/data/lines/$lineId/girouettes/$girouetteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/help'
    | '/legal'
    | '/embed/$networkId'
    | '/'
    | '/data'
    | '/data/networks/$networkId'
    | '/data/vehicles/$vehicleId'
    | '/data/lines/$lineId/girouettes'
    | '/data/lines/$lineId/vehicle-assignments'
    | '/data/lines/$lineId'
    | '/data/lines/$lineId/girouettes/new'
    | '/data/lines/$lineId/girouettes/$girouetteId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/help'
    | '/_app/legal'
    | '/embed/$networkId'
    | '/_app/'
    | '/_app/data/'
    | '/_app/data/networks/$networkId'
    | '/_app/data/vehicles/$vehicleId'
    | '/_app/data/lines/$lineId/girouettes'
    | '/_app/data/lines/$lineId/vehicle-assignments'
    | '/_app/data/lines/$lineId/'
    | '/_app/data/lines/$lineId/girouettes_/new'
    | '/_app/data/lines/$lineId/girouettes_/$girouetteId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  EmbedNetworkIdRoute: typeof EmbedNetworkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/embed/$networkId': {
      id: '/embed/$networkId'
      path: '/embed/$networkId'
      fullPath: '/embed/$networkId'
      preLoaderRoute: typeof EmbedNetworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/legal': {
      id: '/_app/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/': {
      id: '/_app/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof AppDataIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/vehicles/$vehicleId': {
      id: '/_app/data/vehicles/$vehicleId'
      path: '/data/vehicles/$vehicleId'
      fullPath: '/data/vehicles/$vehicleId'
      preLoaderRoute: typeof AppDataVehiclesVehicleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/networks/$networkId': {
      id: '/_app/data/networks/$networkId'
      path: '/data/networks/$networkId'
      fullPath: '/data/networks/$networkId'
      preLoaderRoute: typeof AppDataNetworksNetworkIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/lines/$lineId/': {
      id: '/_app/data/lines/$lineId/'
      path: '/data/lines/$lineId'
      fullPath: '/data/lines/$lineId/'
      preLoaderRoute: typeof AppDataLinesLineIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/lines/$lineId/vehicle-assignments': {
      id: '/_app/data/lines/$lineId/vehicle-assignments'
      path: '/data/lines/$lineId/vehicle-assignments'
      fullPath: '/data/lines/$lineId/vehicle-assignments'
      preLoaderRoute: typeof AppDataLinesLineIdVehicleAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/lines/$lineId/girouettes': {
      id: '/_app/data/lines/$lineId/girouettes'
      path: '/data/lines/$lineId/girouettes'
      fullPath: '/data/lines/$lineId/girouettes'
      preLoaderRoute: typeof AppDataLinesLineIdGirouettesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/lines/$lineId/girouettes_/new': {
      id: '/_app/data/lines/$lineId/girouettes_/new'
      path: '/data/lines/$lineId/girouettes/new'
      fullPath: '/data/lines/$lineId/girouettes/new'
      preLoaderRoute: typeof AppDataLinesLineIdGirouettesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/lines/$lineId/girouettes_/$girouetteId/edit': {
      id: '/_app/data/lines/$lineId/girouettes_/$girouetteId/edit'
      path: '/data/lines/$lineId/girouettes/$girouetteId/edit'
      fullPath: '/data/lines/$lineId/girouettes/$girouetteId/edit'
      preLoaderRoute: typeof AppDataLinesLineIdGirouettesGirouetteIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHelpRoute: typeof AppHelpRoute
  AppLegalRoute: typeof AppLegalRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDataIndexRoute: typeof AppDataIndexRoute
  AppDataNetworksNetworkIdRoute: typeof AppDataNetworksNetworkIdRoute
  AppDataVehiclesVehicleIdRoute: typeof AppDataVehiclesVehicleIdRoute
  AppDataLinesLineIdGirouettesRoute: typeof AppDataLinesLineIdGirouettesRoute
  AppDataLinesLineIdVehicleAssignmentsRoute: typeof AppDataLinesLineIdVehicleAssignmentsRoute
  AppDataLinesLineIdIndexRoute: typeof AppDataLinesLineIdIndexRoute
  AppDataLinesLineIdGirouettesNewRoute: typeof AppDataLinesLineIdGirouettesNewRoute
  AppDataLinesLineIdGirouettesGirouetteIdEditRoute: typeof AppDataLinesLineIdGirouettesGirouetteIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHelpRoute: AppHelpRoute,
  AppLegalRoute: AppLegalRoute,
  AppIndexRoute: AppIndexRoute,
  AppDataIndexRoute: AppDataIndexRoute,
  AppDataNetworksNetworkIdRoute: AppDataNetworksNetworkIdRoute,
  AppDataVehiclesVehicleIdRoute: AppDataVehiclesVehicleIdRoute,
  AppDataLinesLineIdGirouettesRoute: AppDataLinesLineIdGirouettesRoute,
  AppDataLinesLineIdVehicleAssignmentsRoute:
    AppDataLinesLineIdVehicleAssignmentsRoute,
  AppDataLinesLineIdIndexRoute: AppDataLinesLineIdIndexRoute,
  AppDataLinesLineIdGirouettesNewRoute: AppDataLinesLineIdGirouettesNewRoute,
  AppDataLinesLineIdGirouettesGirouetteIdEditRoute:
    AppDataLinesLineIdGirouettesGirouetteIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  EmbedNetworkIdRoute: EmbedNetworkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
