##########################################
# STAGE 1 - Build project artifacts      #
##########################################

FROM node:22.10.0-slim AS builder
WORKDIR /bus-tracker
RUN corepack enable

# Fetch dependencies
COPY pnpm-lock.yaml ./
RUN pnpm fetch

# Install dependencies
COPY libraries/contracts/ ./libraries/contracts/
COPY apps/client/ ./apps/client/
RUN pnpm install -r

# Build client
RUN pnpm -r build

##########################################
# STAGE 2 - Run distribution app         #
##########################################

FROM nginx:1.27.0-alpine AS web
WORKDIR /usr/share/nginx/html

# Copy nginx configuration
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copy build artifacts
COPY --from=builder /bus-tracker/apps/client/dist/ ./
