##########################################
# STAGE 1 - Build project artifacts      #
##########################################

FROM node:22.14.0-alpine AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /bus-tracker

RUN npm install -g corepack@latest
RUN corepack enable

# Fetch dependencies
COPY pnpm-lock.yaml ./
RUN pnpm fetch

# Install dependencies
COPY libraries/contracts/ ./libraries/contracts/
COPY apps/server/ ./apps/server/
RUN pnpm install -r

# Build server
RUN pnpm -r build

# Deploy server
RUN pnpm deploy --legacy --filter=@bus-tracker/server --prod server-deployment

##########################################
# STAGE 2 - Run distribution app         #
##########################################

FROM oven/bun:1.2.5-slim AS runtime
WORKDIR /bus-tracker
ENV NODE_ENV=production

# Copy project artifacts
COPY --from=builder /bus-tracker/server-deployment/node_modules ./server/node_modules/
COPY --from=builder /bus-tracker/server-deployment/drizzle ./server/drizzle/
COPY --from=builder /bus-tracker/server-deployment/dist ./server/

CMD ["bun", "run", "/bus-tracker/server/index.js"]


