##########################################
# STAGE 1 - Build project artifacts      #
##########################################

FROM node:22.21.0 AS builder
WORKDIR /bus-tracker
RUN npm install -g corepack@latest
RUN corepack enable

# Fetch dependencies
# COPY patches/ ./patches/
COPY pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm fetch

# Install dependencies
COPY libraries/contracts/ ./libraries/contracts/
COPY apps/client/ ./apps/client/
RUN pnpm install -r

# Inject build information
ARG BUILD_HASH
ENV VITE_BUILD_HASH=${BUILD_HASH}

ARG BUILD_TIMESTAMP
ENV VITE_BUILD_TIMESTAMP=${BUILD_TIMESTAMP}

# Build client
RUN pnpm -r build

##########################################
# STAGE 2 - Run distribution app         #
##########################################

FROM nginx:1.29.1-alpine AS web
WORKDIR /usr/share/nginx/html

# Copy nginx configuration
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copy build artifacts
COPY --from=builder /bus-tracker/apps/client/dist/ ./
