FROM node:25.8.1-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /bus-tracker

##########################################
# STAGE 1 - Build project artifacts      #
##########################################

FROM base AS builder
RUN npm install -g --force corepack@latest
RUN corepack enable

# Fetch dependencies
COPY pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm fetch

# Install dependencies
COPY libraries/contracts/ ./libraries/contracts/
COPY apps/server/ ./apps/server/
RUN pnpm install -r

# Build server
RUN pnpm -r build

# Deploy server
RUN pnpm deploy --legacy --filter=@bus-tracker/server --prod server-deployment

##########################################
# STAGE 2 - Run distribution app         #
##########################################

FROM oven/bun:1.3.11-alpine AS runtime
ENV NODE_ENV=production

RUN apk add --no-cache tini curl

WORKDIR /bus-tracker/server

# Copy project artifacts
COPY --from=builder /bus-tracker/server-deployment/node_modules ./node_modules/
COPY --from=builder /bus-tracker/server-deployment/drizzle ./drizzle/
COPY --from=builder /bus-tracker/server-deployment/dist ./
COPY --from=builder /bus-tracker/server-deployment/src ./src/
COPY --from=builder /bus-tracker/server-deployment/.env ./.env

USER bun
CMD ["/sbin/tini", "--", "bun", "run", "--env-file", ".env", "src/index.ts"]

