name: Deployment

on:
  push:
    branches: ['main']
    paths:
      - apps/client/**/*
      - apps/server/**/*
      - docker/**/*
      - libraries/**/*
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - .github/workflows/deployment.yaml

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        component: ['client', 'server']

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Copy environment files
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > apps/client/.env
          echo "${{ secrets.SERVER_ENV }}" > apps/server/.env

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Log in to the Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.component }}
          tags: type=sha,format=long
    
      - name: Generate build information
        id: build-info
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_time=$(date +'%Y-%m-%dT%H:%M:%S%:z')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_HASH=${{ steps.build-info.outputs.short_sha }}
            BUILD_TIMESTAMP=${{ steps.build-info.outputs.build_time }}
          context: .
          file: docker/Dockerfile-${{ matrix.component }}
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: ['build']

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy stack to the server
        uses: kitconcept/docker-stack-deploy@1a7a5e778d08cf92bda2ebbd068fe0ca078d09c8
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          remote_host: ${{ secrets.DEPLOY_SSH_HOST }}
          remote_port: ${{ secrets.DEPLOY_SSH_PORT }}
          remote_user: ${{ secrets.DEPLOY_SSH_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          stack_file: "docker/bus-tracker-stack.yaml"
          stack_name: "bus-tracker"
